### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by imaginaryusername** [unitecash/unite-client#2]
Under Fedora 27: `npm build` leads to 

```ERROR in ./src/client/js/App.js
Module not found: Error: Can't resolve './Name' in '/home/user/bin/unite-client/src/client/js'
 @ ./src/client/js/App.js 65:0-25 66:14-18

ERROR in ./src/client/js/App.js
Module not found: Error: Can't resolve './Post' in '/home/user/bin/unite-client/src/client/js'
 @ ./src/client/js/App.js 63:0-25 64:14-18

ERROR in ./src/client/js/App.js
Module not found: Error: Can't resolve './Transaction' in '/home/user/bin/unite-client/src/client/js'
 @ ./src/client/js/App.js 59:0-39 60:21-32
```

Did I miss something?

**Comment by ty-everett** [comment]
I apologize for the extended delay in replying. I've only tested it on Windows, but you might try adding ".js" to the end of each of the imports in App.js. I'll fix this in the next commit, but that will be a while since I'm moving things around and moving to React/JSX.
You might try opening the "index.html" file from "public" in a browser, I believe the last commit had a working app.js in it.
Let me know if adding the extension doesn't work
